### PR TITLE
Readded AIMBUINO, CRAZYCAR and FOOTUINO

### PR DESCRIPTION
**Pull request by ogbaba**
Hello ! I compiled the three games with the version 4 of the library so they are up-to-date again

### CODE REVIEW

**Comment by Rodot** [comment]
Hello,
Thank you for your commit, but I reduced the number of games on purpose to motive people to go on the website and download new ones. It would be great if you could make a pull request directly to these game's repo instead :)

**Comment by ogbaba** [comment]
Okay I will do that 😃

**Comment by ogbaba** [comment]
Well that's weird the games page http://gamebuino.com/wiki/index.php?title=Games is linking to this repo 😕

**Comment by Rodot** [comment]
I fixed it, thanks for pointing this out :)

**Pull request closed without merging**
